"""
List01 - Zad 2
"""

first_word = input("Podaj pierwsze słowo: ")
second_word = input("Podaj drugie słowo: ")

first_word = first_word.replace("a", '7')
first_word = first_word.replace("A", '7')
first_word = first_word.replace("e", '7')
first_word = first_word.replace("E", '7')
first_word = first_word.replace("i", '7')
first_word = first_word.replace("I", '7')
first_word = first_word.replace("o", '7')
first_word = first_word.replace("O", '7')
first_word = first_word.replace("u", '7')
first_word = first_word.replace("U", '7')
first_word = first_word.replace("y", '7')
first_word = first_word.replace("Y", '7')

second_word = second_word.replace("b", '6')
second_word = second_word.replace("B", '6')
second_word = second_word.replace("c", '6')
second_word = second_word.replace("C", '6')
second_word = second_word.replace("d", '6')
second_word = second_word.replace("D", '6')
second_word = second_word.replace("f", '6')
second_word = second_word.replace("F", '6')
second_word = second_word.replace("g", '6')
second_word = second_word.replace("G", '6')
second_word = second_word.replace("h", '6')
second_word = second_word.replace("H", '6')
second_word = second_word.replace("j", '6')
second_word = second_word.replace("J", '6')
second_word = second_word.replace("k", '6')
second_word = second_word.replace("K", '6')
second_word = second_word.replace("l", '6')
second_word = second_word.replace("L", '6')
second_word = second_word.replace("m", '6')
second_word = second_word.replace("M", '6')
second_word = second_word.replace("n", '6')
second_word = second_word.replace("N", '6')
second_word = second_word.replace("p", '6')
second_word = second_word.replace("P", '6')
second_word = second_word.replace("q", '6')
second_word = second_word.replace("Q", '6')
second_word = second_word.replace("r", '6')
second_word = second_word.replace("R", '6')
second_word = second_word.replace("s", '6')
second_word = second_word.replace("S", '6')
second_word = second_word.replace("t", '6')
second_word = second_word.replace("T", '6')
second_word = second_word.replace("v", '6')
second_word = second_word.replace("V", '6')
second_word = second_word.replace("x", '6')
second_word = second_word.replace("X", '6')
second_word = second_word.replace("z", '6')
second_word = second_word.replace("Z", '6')

joint_words = first_word + second_word
joint_words = joint_words.upper()

print(joint_words)
